// --------------------------------------------------------------------------------------------------------------------
// <copyright file="DateTimeExtensions.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.DateTime.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.DateTime.Recipes
{
    /// <summary>
    /// Extension methods on <see cref="DateTime"/>.
    /// </summary>
#if !OBeautifulCodeDateTimeRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.DateTime.Recipes", "See package version number")]
    internal
#else
    public
#endif
    class DateTimeExtensions
    {
    }
}
